language: python

sudo: false

env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37

install:
  - pip install -q tox 

  # coverage is only measured and published for py37
  - if [[ $TOXENV == "py37" ]]; then
        pip install -q coverage coveralls;
    fi


script:
  - tox -e $TOXENV

after_success:
  - if [[ $TOXENV == "py37" ]]; then
        coveralls;
    fi

notifications:
  email:
    - contact@jeffquast.com
